### ISSUE TITLE
On Ubuntu 22.04LTS, I have an issue with compiling the aseprite. 

### ISSUE THREAD

**Issue by RenegadeCash** [aseprite/aseprite#3381]
knand@knand:~/aseprite/build$ cmake       -DCMAKE_BUILD_TYPE=RelWithDebInfo       -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++       -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++       -DLAF_BACKEND=skia       -DSKIA_DIR=$HOME/deps/skia       -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64       -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a       -G Ninja ..
CMake Deprecation Warning at CMakeLists.txt:17 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The CXX compiler identification is Clang 14.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/knand/aseprite/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/home/knand/deps/depot_tools/ninja cmTC_4c5ed && [1/2] Building CXX object CMakeFiles/cmTC_4c5ed.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_4c5ed
    FAILED: cmTC_4c5ed 
    : && /usr/bin/clang++ -stdlib=libc++ -stdlib=libc++ CMakeFiles/cmTC_4c5ed.dir/testCXXCompiler.cxx.o -o cmTC_4c5ed   && :
    /usr/bin/ld: cannot find -lc++abi: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (project)

-- Configuring incomplete, errors occurred!
See also "/home/knand/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "/home/knand/aseprite/build/CMakeFiles/CMakeError.log".
knand@knand:~/aseprite/build$

**Comment by RenegadeCash** [comment]
I cloned the latest branches of skia and aseprite

**Comment by Knand1861** [comment]
I've found out there's something wrong with clang. I tried compiling this:

///////////////////
#include<iostream>
int main(){
for (int i =0;i<10;i++){
std::cout<<i<<"\n";
}
return 0;
}
///////////////////

with g++ and it worked, while clang throws an error:
adf.c:1:9: fatal error: 'iostream' file not found

I'm not really experienced with linux yet. Tried to reinstall clang and it didn't help. Looks like the issue is not about aseprite itself, but could you be so nice and explain what the hell is wrong with clang?

**Comment by arthurpaulino** [comment]
I got farther with this: https://stackoverflow.com/questions/62612405/usr-bin-ld-cannot-find-lc

Basically: `sudo apt install libc++-11-dev libc++abi-11-dev`

**Comment by Inve1951** [comment]
> ```
> #include <sstream>
>          ^~~~~~~~
> ```
The problem is missing include directories/files.
For me the solution was to install `libc++-10-dev libc++abi-10-dev libstdc++-10-dev clang-10 gcc-10 g++-10` (instead of 11 or no specific version; ubuntu) and to declare these variables prior running cmake:
```sh
export CC=clang-10
export CXX=clang++-10
export CPLUS_INCLUDE_PATH=/usr/include/c++/10:/usr/include/x86_64-linux-gnu/c++/10
```
more info: https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found

**Comment by ChaseClark** [comment]
I was able to compile on Ubuntu 22.04 by installing 
--> "clang libc++-dev libc++abi-dev" **instead of** 
-->"clang-10 libc++-10-dev libc++abi-10-dev"
for the Ubuntu/Debian dependencies.
