### ISSUE TITLE
src/app/document_range_tests.cpp does not build on Linux

### ISSUE THREAD

**Issue by agateau** [aseprite/aseprite#664]
The build failure I fixed in #644 is back. The calls to "notifyActiveSiteChanged()" must be prefixed with "this->".

~~~
[100%] Building CXX object src/CMakeFiles/file_tests.dir/app/file/file_tests.cpp.o
In file included from /home/aurelien/.cache/nanoci/aseprite/src/src/app/document_range_tests.cpp:19:0:
/home/aurelien/.cache/nanoci/aseprite/src/src/./doc/test_context.h: In member function ‘void doc::TestContextT<Base>::onAddDocument
/home/aurelien/.cache/nanoci/aseprite/src/src/./doc/test_context.h:40:31: error: there are no arguments to ‘notifyActiveSiteChanged
       notifyActiveSiteChanged();                                                   
                               ^                                                    
~~~

**Comment by dacap** [comment]
Thanks for reporting this @agateau, I'll fix compiling issues before I tag. At least I'll try to compile on gcc before I tag. The general idea from now on will be to keep tags compilable on three compilers.

Another approach that I'm thinking of is not pushing commits until I reach a new release. Which looks pretty reasonable because I'm getting too much compiling issues reported.

**Comment by agateau** [comment]
Delaying fixing of compiling issues before you tag sounds like a bad idea: it won't let anyone bisect for regressions.

Have you considered setting up something like [Travis](http://travis-ci.org)? This would help you catch build (and test) failures faster.

**Comment by dacap** [comment]
I've considered Travis but anyway I don't have gcc at hand (on Windows) to fix a compilation problem quickly. At the moment the compilers priority is VS, clang, gcc. I work daily with VS and compile in clang in periods of two or three days. (I almost never compile in gcc.)

My priorities are: customer support, bug fixing, new features, and at the end, compiling problems.

**Comment by agateau** [comment]
OK. Note that this fails with clang as well.

**Comment by agateau** [comment]
Would it be easier for you if I provided pull requests instead of filling issues? I am a happy Aseprite user and would like to keep it running on Linux (hey, if you ever provide binaries for Linux I'll be happy to be a customer even)

**Comment by dacap** [comment]
I'd love to receive pull requests for this kind of issues :heart_eyes:

(After v1.1-beta3, I'll start dedicating some time to Linux binaries)
