### ISSUE TITLE
Cannot build on windows if Haskell Platform (8.2.2 64-bit) is Installed

### ISSUE THREAD

**Issue by sirdigbot** [aseprite/aseprite#1690]
While building from source with Skia back-end, when running the final `ninja aseprite` command, I got this error:
```
In file included from ../third_party/curl/lib/url.c:119:0:
../third_party/curl/lib/select.h:66:8: error: redefinition of 'struct pollfd'
 struct pollfd
        ^~~~~~
In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/url.c:25:
D:/Programs/Haskell Platform/8.2.2/mingw/x86_64-w64-mingw32/include/winsock2.h:1155:16: note: origin
ally defined here
 typedef struct pollfd {
                ^~~~~~
[10/1239] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/strequal.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
ninja: build stopped: subcommand failed.
```  
Uninstalling Haskell Platform resolves the issue.  
It seems Haskell Platform (8.2.2 64-bit) adds files to the PATH variable that are picked up during the CMake build.  

### Aseprite and System version

* Aseprite version: 1.2.7.2 (Building with Skia)
* System: Windows 8.1 64-bit

**Comment by dacap** [comment]
I'll label this as `wontfix` just because the `PATH` shouldn't include information about other compilers, or this is a cmake issue. Anyway it's nice to have the issue open just in case other people has this same problem knows the solution.
