### ISSUE TITLE
Could not convert ‘LayerImage’ from ‘doc::ObjectType’ to ‘int’

### ISSUE THREAD

**Issue by 3vi1** [aseprite/aseprite#507]
I've built this in the past, but since the recent updates in master it is failing to compile on Ubuntu 14.10.

```
[ 45%] Building CXX object src/doc/CMakeFiles/doc-lib.dir/layer_io.cpp.o
/home/evil/src/aseprite/src/doc/layer_io.cpp: In function ‘doc::Layer* doc::read_layer(std::istream&, doc::LayerSubObjectsSerializer*, doc::Sprite*)’:
/home/evil/src/aseprite/src/doc/layer_io.cpp:95:22: error: could not convert ‘LayerImage’ from ‘doc::ObjectType’ to ‘int’
     case ObjectType::LayerImage: {
                      ^
/home/evil/src/aseprite/src/doc/layer_io.cpp:116:22: error: could not convert ‘LayerFolder’ from ‘doc::ObjectType’ to ‘int’
     case ObjectType::LayerFolder: {
                      ^
src/doc/CMakeFiles/doc-lib.dir/build.make:652: recipe for target 'src/doc/CMakeFiles/doc-lib.dir/layer_io.cpp.o' failed
make[2]: *** [src/doc/CMakeFiles/doc-lib.dir/layer_io.cpp.o] Error 1
CMakeFiles/Makefile2:3567: recipe for target 'src/doc/CMakeFiles/doc-lib.dir/all' failed
make[1]: *** [src/doc/CMakeFiles/doc-lib.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```
