### ISSUE TITLE
Cannot compile on ubuntu 18.04 ‘MakeModeFilter’ is not a member of ‘SkColorFilter’

### ISSUE THREAD

**Issue by F4HVO** [aseprite/aseprite#2288]
Trying to compile aseprite after successfully compiling skia.

`
cmake       -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_OS_BACKEND=skia       -DSKIA_DIR=/home/hugo/deps/skia -DSKIA_OUT_DIR=/home/hugo/deps/skia/out/Release-x64 -G Ninja       ..
`

This results in 

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SKIA_SKCMS_INCLUDE_DIR

Then
`
cmake       -DCMAKE_BUILD_TYPE=RelWithDebInfo       -DLAF_OS_BACKEND=skia       -DSKIA_DIR=/home/hugo/deps/skia       -DSKIA_OUT_DIR=/home/hugo/deps/skia/out/Release-x64     -DSKIA_SKCMS_INCLUDE_DIR=/home/hugo/deps/skia/include/third_party/skcms/  -G Ninja       ..
`
> Build files have been written to: /home/hugo/workingCopies/aseprite/build

Then 
`
ninja aseprite
` 
> /home/hugo/deps/skia/include/core/SkColorSpace.h:11:10: fatal error: include/core/SkTypes.h: No such file or directory
 #include "include/core/SkTypes.h"  // needed to allow the LEGACY flags to be defined
          ^~~~~~~~~~~~~~~~~~~~~~~~

Then I added include_directories(/home/hugo/deps/skia) in CMakeLists.txt
`
ninja aseprite
` 

> ../laf/os/skia/skia_surface.h:544:22: error: ‘MakeModeFilter’ is not a member of ‘SkColorFilter’
       SkColorFilter::MakeModeFilter(to_skia(fg), SkBlendMode::kSrcIn));

I have tried this with the source from Aseprite-v1.2.16.2-Source.zip (after a previous attempt with a checkout of master).

### Aseprite and System version

* Aseprite version: Aseprite-v1.2.16.2-Source.zip
* System: Ubuntu 18.04

**Comment by F4HVO** [comment]
The required function seem to have disappeared there : https://github.com/aseprite/skia/commit/b286bc2da8e5f7b2f90246237ffbda31875f9863#diff-d8a8e009ba6290582eba4f2882abafab

**Comment by F4HVO** [comment]
Wen through the process a few times more. Here are a few errors I made :
- not using gcc-9
- using last aseprite release and last skia release

When using gcc-9 (version 9.2.1), aseprite master checkout and skia-m81 from https://github.com/aseprite/skia/releases : Skia-Linux-Release-x64.zip.

I still cannot compile. I have a lot of undefined reference :
> /home/hugo/deps/skia/out/Release-x64/libskia.a(libpiex.range_checked_byte_ptr.o): In function `piex::binary_parse::strlen(piex::binary_parse::RangeCheckedBytePtr const&)':
range_checked_byte_ptr.cc:(.text._ZN4piex12binary_parse6strlenERKNS0_19RangeCheckedBytePtrE+0x95): undefined reference to `std::__1::__shared_weak_count::__release_weak()'

> /home/hugo/deps/skia/out/Release-x64/libskia.a(libpiex.image_type_recognition_lite.o): In function `piex::image_type_recognition::(anonymous namespace)::ArwTypeChecker::IsMyType(piex::binary_parse::RangeCheckedBytePtr const&) const':
image_type_recognition_lite.cc:(.text._ZNK4piex22image_type_recognition12_GLOBAL__N_114ArwTypeChecker8IsMyTypeERKNS_12binary_parse19RangeCheckedBytePtrE+0x1ba): undefined reference to `std::__1::__shared_weak_count::__release_weak()'

I seems libskia and aseprite are not built with the same compiler version.

**Comment by F4HVO** [comment]
I am getting closer.
I changed the default compiler on my machine to gcc-9 g++-9 as I suspected there was a compiler version mismatch.
No I have another error :

>  [1490/1490] Linking CXX executable bin/aseprite
FAILED: bin/aseprite 
: && /usr/bin/c++  -Wall -Wno-switch -O2 -g -DNDEBUG   src/CMakeFiles/aseprite.dir/main/main.cpp.o  -o bin/aseprite  -Wl,-rpath,/usr/local/lib:  lib/libapp-lib.a  lib/libclip.a  -lxcb  -lpthread  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/hugo/deps/skia/out/Release-x64/libskia.a  /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/x86_64-linux-gnu/libfontconfig.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXext.so  /usr/lib/x86_64-linux-gnu/libXcursor.so  /home/hugo/deps/skia/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libwebpdemux.a  lib/libwebpmux.a  lib/libwebp.a  -lpthread  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  -lm  /usr/lib/x86_64-linux-gnu/libbz2.so  lib/libjson11.a  lib/libarchive.a  /usr/lib/x86_64-linux-gnu/libb2.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/libnettle.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/lib/x86_64-linux-gnu/libexpat.so  /usr/local/lib/librichacl.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libupdater-lib.a  lib/libcfg-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  /usr/lib/x86_64-linux-gnu/libdl.so  lib/libcurl.a  lib/libz.a  -ldl && :
lib/liblualib.a(loslib.c.o): In function `os_tmpname':
/home/hugo/workingCopies/aseprite/build/../third_party/lua/loslib.c:169: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
lib/libarchive.a(archive_write_disk_posix.c.o): In function `_archive_write_disk_finish_entry':
/home/hugo/workingCopies/aseprite/build/../third_party/libarchive/libarchive/archive_write_disk_posix.c:1817: undefined reference to `archive_write_disk_set_acls'
lib/libarchive.a(archive_write_disk_posix.c.o): In function `_archive_write_disk_close':
/home/hugo/workingCopies/aseprite/build/../third_party/libarchive/libarchive/archive_write_disk_posix.c:2416: undefined reference to `archive_write_disk_set_acls'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by F4HVO** [comment]
Turns out I had another version of librichacl wich was used instead of the one buldled with aseprite. Now it works.
To sum up, here is what happened if someone else has the same problems :
- be sure you default gcc and g++ version are 9.2 (do not try to use environment variables or cmake variables to force the use of a version of gcc and g++, at some point in the build process they will be ignored)
- Use last version of skia and aseprite, build from source, be sure that you do not already have librairies that are provided with these checkouts
- if that goes wrong do not try to fix the build process, the problem is very likely that your initial configuration is not correct.

Hope this helps someone.
